'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Compras', [
      {
        fecha: new Date(),
        numeroCompra: 1,
        monto: 23,
        estado: 'Pendiente',
        factura: '1',
        nombre: 'PC',
        idSubsidio: 1,
        idProveedor: 1,
        subRubro: 'Ejemplo subRubro',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        fecha: new Date(),
        numeroCompra: 1,
        monto: 23,
        estado: 'Pendiente',
        factura: '1',
        nombre: 'PC',
        idSubsidio: 2,
        idProveedor: 2,
        subRubro: 'Ejemplo subRubro',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        fecha: new Date(),
        numeroCompra: 1,
        monto: 23,
        estado: 'Pendiente',
        factura: '1',
        nombre: 'PC',
        idSubsidio: 3,
        idProveedor: 3,
        subRubro: 'Ejemplo subRubro',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        fecha: new Date(),
        numeroCompra: 1,
        monto: 23,
        estado: 'Pendiente',
        factura: '1',
        nombre: 'PC',
        idSubsidio: 4,
        idProveedor: 4,
        subRubro: 'Ejemplo subRubro',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        fecha: new Date(),
        numeroCompra: 1,
        monto: 23,
        estado: 'Aprobado',
        factura: '1',
        nombre: 'PC',
        idSubsidio: 5,
        idProveedor: 5,
        subRubro: 'Ejemplo subRubro',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        fecha: new Date(),
        numeroCompra: 1,
        monto: 23,
        estado: 'Aprobado',
        factura: '1',
        nombre: 'PC',
        idSubsidio: 6,
        idProveedor: 6,
        subRubro: 'Ejemplo subRubro',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        fecha: new Date(),
        numeroCompra: 1,
        monto: 23,
        estado: 'Aprobado',
        factura: '1',
        nombre: 'PC',
        idSubsidio: 1,
        idProveedor: 7,
        subRubro: 'Ejemplo subRubro',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        fecha: new Date(),
        numeroCompra: 1,
        monto: 23,
        estado: 'Aprobado',
        factura: '1',
        nombre: 'PC',
        idSubsidio: 2,
        idProveedor: 8,
        subRubro: 'Ejemplo subRubro',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Compras', null, {});
  },
};
